# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baiduchengxu.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(892, 834)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 891, 821))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.listView.setFont(font)
        self.listView.setStyleSheet("\n"
"background-image: url(:/bearwn.WEBP);")
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(920, 110, 631, 71))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 290, 621, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.kaishi_2 = QtWidgets.QLabel(self.centralwidget)
        self.kaishi_2.setGeometry(QtCore.QRect(110, 220, 81, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.kaishi_2.setFont(font)
        self.kaishi_2.setObjectName("kaishi_2")
        self.zhongzhi_2 = QtWidgets.QLabel(self.centralwidget)
        self.zhongzhi_2.setGeometry(QtCore.QRect(280, 220, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.zhongzhi_2.setFont(font)
        self.zhongzhi_2.setObjectName("zhongzhi_2")
        self.baiduyixia = QtWidgets.QPushButton(self.centralwidget)
        self.baiduyixia.setGeometry(QtCore.QRect(610, 140, 121, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 0.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(0, 0, 0))
        gradient.setColorAt(1.0, QtGui.QColor(255, 255, 255))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.baiduyixia.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.baiduyixia.setFont(font)
        self.baiduyixia.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"")
        self.baiduyixia.setObjectName("baiduyixia")
        self.kaishi = QtWidgets.QSpinBox(self.centralwidget)
        self.kaishi.setGeometry(QtCore.QRect(200, 220, 80, 30))
        self.kaishi.setObjectName("kaishi")
        self.zhongzhi = QtWidgets.QSpinBox(self.centralwidget)
        self.zhongzhi.setGeometry(QtCore.QRect(370, 220, 80, 30))
        self.zhongzhi.setObjectName("zhongzhi")
        self.tupiansousuo = QtWidgets.QTextEdit(self.centralwidget)
        self.tupiansousuo.setGeometry(QtCore.QRect(110, 140, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.tupiansousuo.setFont(font)
        self.tupiansousuo.setStyleSheet("background-color: rgba(250, 255, 255, 120);")
        self.tupiansousuo.setObjectName("tupiansousuo")
        self.xiazaixinxizhanshi = QtWidgets.QTextEdit(self.centralwidget)
        self.xiazaixinxizhanshi.setGeometry(QtCore.QRect(100, 370, 611, 321))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.xiazaixinxizhanshi.setFont(font)
        self.xiazaixinxizhanshi.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.xiazaixinxizhanshi.setObjectName("xiazaixinxizhanshi")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 90, 101, 31))
        self.label_4.setObjectName("label_4")
        self.lianjie_1 = QtWidgets.QLabel(self.centralwidget)
        self.lianjie_1.setGeometry(QtCore.QRect(200, 90, 81, 31))
        self.lianjie_1.setObjectName("lianjie_1")
        self.lianjie_3 = QtWidgets.QLabel(self.centralwidget)
        self.lianjie_3.setGeometry(QtCore.QRect(380, 90, 81, 31))
        self.lianjie_3.setObjectName("lianjie_3")
        self.lianjie_2 = QtWidgets.QLabel(self.centralwidget)
        self.lianjie_2.setGeometry(QtCore.QRect(290, 90, 81, 31))
        self.lianjie_2.setObjectName("lianjie_2")
        self.cipan = QtWidgets.QTextEdit(self.centralwidget)
        self.cipan.setGeometry(QtCore.QRect(480, 220, 120, 30))
        self.cipan.setObjectName("cipan")
        self.wenjianming = QtWidgets.QTextEdit(self.centralwidget)
        self.wenjianming.setGeometry(QtCore.QRect(609, 220, 120, 30))
        self.wenjianming.setObjectName("wenjianming")
        self.listView.raise_()
        self.label_2.raise_()
        self.baiduyixia.raise_()
        self.xiazaixinxizhanshi.raise_()
        self.label_3.raise_()
        self.tupiansousuo.raise_()
        self.kaishi_2.raise_()
        self.kaishi.raise_()
        self.zhongzhi_2.raise_()
        self.zhongzhi.raise_()
        self.label_4.raise_()
        self.lianjie_1.raise_()
        self.lianjie_3.raise_()
        self.lianjie_2.raise_()
        self.cipan.raise_()
        self.wenjianming.raise_()
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "                                                                                                                                                                       百度图片批量下载系统"))
        self.listView.setToolTip(_translate("mainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:30pt; font-weight:600;\">                软件运行结果 </span></p></body></html>"))
        self.kaishi_2.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#070606;\">开始页数</span></p></body></html>"))
        self.zhongzhi_2.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">终止页数</span></p></body></html>"))
        self.baiduyixia.setToolTip(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">开始下载</span></p></body></html>"))
        self.baiduyixia.setText(_translate("mainWindow", "百度一下"))
        self.tupiansousuo.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:15pt;\"><br /></p></body></html>"))
        self.xiazaixinxizhanshi.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Agency FB\'; font-size:12pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
        self.label_4.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">热门搜索：</span></p></body></html>"))
        self.lianjie_1.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><a href=\"https://image.baidu.com/search/index?tn=baiduimage&amp;ipn=r&amp;ct=201326592&amp;cl=2&amp;lm=-1&amp;st=-1&amp;fr=&amp;sf=1&amp;fmq=1526269427171_R&amp;pv=&amp;ic=0&amp;nc=1&amp;z=&amp;se=1&amp;showtab=0&amp;fb=0&amp;width=&amp;height=&amp;face=0&amp;istype=2&amp;ie=utf-8&amp;word=%E5%A3%81%E7%BA%B8\"><span style=\" font-size:16pt; text-decoration: underline; color:#0000ff;\">壁纸</span></a></p></body></html>"))
        self.lianjie_3.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><a href=\"https://image.baidu.com/search/albumslist?tn=albumslist&amp;word=%E8%9B%8B%E7%B3%95&amp;album_tab=%E4%BA%BA%E7%89%A9&amp;rn=15&amp;fr=albumsdetail_nav\"><span style=\" font-size:16pt; text-decoration: underline; color:#0000ff;\">高清美图</span></a></p></body></html>"))
        self.lianjie_2.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><a href=\"https://image.baidu.com/search/index?tn=baiduimage&amp;ipn=r&amp;ct=201326592&amp;cl=2&amp;lm=-1&amp;st=-1&amp;fr=&amp;sf=1&amp;fmq=1461834053046_R&amp;pv=&amp;ic=0&amp;nc=1&amp;z=&amp;se=1&amp;showtab=0&amp;fb=0&amp;width=&amp;height=&amp;face=0&amp;istype=2&amp;itg=0&amp;ie=utf-8&amp;word=%E5%A4%B4%E5%83%8F#z=0&amp;pn=&amp;ic=0&amp;st=-1&amp;face=0&amp;s=0&amp;lm=-1\"><span style=\" font-size:16pt; text-decoration: underline; color:#0000ff;\">头像</span></a></p></body></html>"))


import gangtiexia_oq
